baseURL = 'https://sidjain1412.github.io/'
languageCode = 'en-us'
title = 'Siddharth Jain'
theme = 'archie'
copyright = "Â© Siddharth"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4
publishDir = "docs"

[params]
favicon = "https://sidjain1412.github.io/images/favicon.png"
mode = "toggle"
useCDN = true
subtitle = "Data Scientist @ [CleverTap](https://clevertap.com)"
description = "Data Scientist @ CleverTap"
aboutme = "**Hello world**"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sidjain1412"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/__sidjain__/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/siddharth-jain1412"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/sidjain1412/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Resume"
url = "/resume_siddharth_jain.pdf"
weight = 4

[[menu.main]]
name = "Bird Map"
url = "https://sidjain1412.github.io/MumbaiBirdMap"
weight = 4

[markup.goldmark.renderer]
unsafe = true
